Repository FEUP-ESOF-2020-21/open-cx-t7g5-5-estrelinhas, pull requests merged in 2020-11, with the labels that each got.

#1 Added Authentication
  src/meetix/lib/controller/AuthController.dart
  src/meetix/lib/main.dart
  src/meetix/lib/view/ConferenceListPage.dart
  src/meetix/lib/view/CreateProfilePage.dart
  src/meetix/lib/view/MyWidgets.dart
  src/meetix/lib/view/SignInPage.dart
  src/meetix/lib/view/SignUpPage.dart
  src/meetix/pubspec.lock
  src/meetix/pubspec.yaml
Labels: enhancement

#2 Merge profile viewer with creating profiles
  src/meetix/lib/main.dart
  src/meetix/lib/model/Profile.dart
  src/meetix/lib/view/ConferenceProfilesPage.dart
  src/meetix/lib/view/MyWidgets.dart
  src/meetix/lib/view/ViewProfileDetailsPage.dart
Labels: enhancement

#18 Liked you page
  README.md
  img/package-diagram.png
  src/meetix/lib/controller/FirestoreController.dart
  src/meetix/lib/view/AllProfilesPage.dart
  src/meetix/lib/view/ConferenceListPage.dart
  src/meetix/lib/view/ConferencePage.dart
  src/meetix/lib/view/CreateProfilePage.dart
  src/meetix/lib/view/LikedYouProfilesPage.dart
  src/meetix/lib/view/ViewProfileDetailsPage.dart
Labels: attendee flow, new feature

#19 Interests & Edit Profile
  src/meetix/lib/model/Conference.dart
  src/meetix/lib/model/Profile.dart
  src/meetix/lib/view/ConferenceProfilesPage.dart
  src/meetix/lib/view/CreateProfilePage.dart
  src/meetix/lib/view/EditProfilePage.dart
  src/meetix/lib/view/MyWidgets.dart
  src/meetix/lib/view/ViewProfileDetailsPage.dart
Labels: attendee flow, firestore, improvement, new feature, user flow

#22 Top20
  src/cloud_functions/.firebaserc
  src/cloud_functions/.gitignore
  src/cloud_functions/firebase.json
  src/cloud_functions/functions/.eslintrc.js
  src/cloud_functions/functions/.gitignore
  src/cloud_functions/functions/package-lock.json
  src/cloud_functions/functions/package.json
  src/cloud_functions/functions/src/index.ts
  src/cloud_functions/functions/tsconfig.json
  src/cloud_functions/package-lock.json
  src/meetix/lib/controller/FunctionsController.dart
  src/meetix/lib/main.dart
  src/meetix/lib/view/ConferenceListPage.dart
  src/meetix/lib/view/ConferencePage.dart
  src/meetix/lib/view/CreateProfilePage.dart
  src/meetix/lib/view/EditProfilePage.dart
  src/meetix/lib/view/MyWidgets.dart
  src/meetix/lib/view/TopProfilesPage.dart
  src/meetix/lib/view/ViewProfileDetailsPage.dart
  src/meetix/pubspec.lock
  src/meetix/pubspec.yaml
Labels: XL, attendee flow, firestore, new feature
